---
apiVersion: v1
kind: Service
metadata:
  name: default-component
  labels:
    app.kubernetes.io/component: default-component
spec:
  type: "ClusterIP"
  ports:
    - port: 9080
      targetPort: 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: default-component