apiVersion: 1
contactPoints:
    - orgId: 1
      name: Vision22 (Teams)
      receivers:
        - uid: fehi06uul6ry8e
          type: teams
          settings:
            url: https://prod-199.westeurope.logic.azure.com:443/workflows/d18d802d1ef645b4a3ebde782d3f0257/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=k9XJNVAwQb3D-oJd1YHHihRftVcgJdfu2wU1Pj-kqqg
          disableResolveMessage: false