apiVersion: 1

groups:
    - orgId: 1
      name: kubernetes-apps
      folder: kubernetes-monitoring
      interval: 1m
      rules:
        - uid: KubePodImagePullBackOff
          title: KubePodImagePullBackOff
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: max_over_time(kube_pod_container_status_waiting_reason{reason="ImagePullBackOff", job!=""}[5m]) >= 1
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in waiting state (reason: "ImagePullBackOff").'
            runbook_url: 'no runbook available'
            summary: Pod cannot pull the image
          labels:
            severity: warning
          isPaused: false

        - uid: KubePodCrashLooping
          title: KubePodCrashLooping
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job!=""}[5m]) >= 1
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in waiting state (reason: "CrashLoopBackOff").'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
            summary: Pod is crash looping.
          labels:
            severity: warning
          isPaused: false

        - uid: KubePodNotReady
          title: KubePodNotReady
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  sum by (namespace, pod, job, cluster) (
                    max by(namespace, pod, job, cluster) (
                      kube_pod_status_phase{job!="", phase=~"Pending|Unknown|Failed"}
                    ) * on(namespace, pod, cluster) group_left(owner_kind) topk by(namespace, pod, cluster) (
                      1, max by(namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"})
                    )
                  ) > 0
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
            summary: Pod has been in a non-ready state for more than 15 minutes.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeDeploymentGenerationMismatch
          title: KubeDeploymentGenerationMismatch
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  kube_deployment_status_observed_generation{job!=""}
                    !=
                  kube_deployment_metadata_generation{job!=""}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this indicates that the Deployment has failed but has not been rolled back.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
            summary: Deployment generation mismatch due to possible roll-back.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeDeploymentReplicasMismatch
          title: KubeDeploymentReplicasMismatch
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  (
                    kube_deployment_spec_replicas{job!=""}
                      >
                    kube_deployment_status_replicas_available{job!=""}
                  ) and (
                    changes(kube_deployment_status_replicas_updated{job!=""}[10m])
                      ==
                    0
                  )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
            summary: Deployment has not matched the expected number of replicas.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeStatefulSetGenerationMismatch
          title: KubeStatefulSetGenerationMismatch
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  kube_statefulset_status_observed_generation{job!=""}
                    !=
                  kube_statefulset_metadata_generation{job!=""}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: StatefulSet generation for {{ $labels.namespace }}/{{ $labels.statefulset }} does not match, this indicates that the StatefulSet has failed but has not been rolled back.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch
            summary: StatefulSet generation mismatch due to possible roll-back.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeStatefulSetUpdateNotRolledOut
          title: KubeStatefulSetUpdateNotRolledOut
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  (
                    max without (revision) (
                      kube_statefulset_status_current_revision{job!=""}
                        unless
                      kube_statefulset_status_update_revision{job!=""}
                    )
                      *
                    (
                      kube_statefulset_replicas{job!=""}
                        !=
                      kube_statefulset_status_replicas_updated{job!=""}
                    )
                  )  and (
                    changes(kube_statefulset_status_replicas_updated{job!=""}[5m])
                      ==
                    0
                  )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} update has not been rolled out.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout
            summary: StatefulSet update has not been rolled out.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeDaemonSetRolloutStuck
          title: KubeDaemonSetRolloutStuck
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  (
                    (
                      kube_daemonset_status_current_number_scheduled{job!=""}
                      !=
                      kube_daemonset_status_desired_number_scheduled{job!=""}
                    ) or (
                      kube_daemonset_status_number_misscheduled{job!=""}
                      !=
                      0
                    ) or (
                      kube_daemonset_status_updated_number_scheduled{job!=""}
                      !=
                      kube_daemonset_status_desired_number_scheduled{job!=""}
                    ) or (
                      kube_daemonset_status_number_available{job!=""}
                      !=
                      kube_daemonset_status_desired_number_scheduled{job!=""}
                    )
                  ) and (
                    changes(kube_daemonset_status_updated_number_scheduled{job!=""}[5m])
                      ==
                    0
                  )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at least 15 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
            summary: DaemonSet rollout is stuck.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeContainerWaiting
          title: KubeContainerWaiting
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  sum by (namespace, pod, container, job, cluster) (kube_pod_container_status_waiting_reason{job!=""}) > 0
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 1h
          annotations:
            description: pod/{{ $labels.pod }} in namespace {{ $labels.namespace }} on container {{ $labels.container}} has been in waiting state for longer than 1 hour.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting
            summary: Pod container waiting longer than 1 hour.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeDaemonSetNotScheduled
          title: KubeDaemonSetNotScheduled
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  kube_daemonset_status_desired_number_scheduled{job!=""}
                    -
                  kube_daemonset_status_current_number_scheduled{job!=""} > 0
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 10m
          annotations:
            description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled
            summary: DaemonSet pods are not scheduled.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeDaemonSetMisScheduled
          title: KubeDaemonSetMisScheduled
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  kube_daemonset_status_number_misscheduled{job!=""} > 0
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          for: 15m
          annotations:
            description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are running where they are not supposed to run.'
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled
            summary: DaemonSet pods are misscheduled.
          labels:
            severity: warning
          isPaused: false

        - uid: KubeJobNotCompleted
          title: KubeJobNotCompleted
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: mimir
              model:
                editorMode: builder
                expr: |
                  time() - max by(namespace, job_name, cluster) (kube_job_status_start_time{job!=""}
                    and
                  kube_job_status_active{job!=""} > 0) > 43200
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
          noDataState: NoData
          execErrState: Error
          annotations:
            description: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" | humanizeDuration }} to complete.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobnotcompleted
            summary: Job did not complete in time.
          labels:
            severity: warning
          isPaused: false