scmAppsetRequeueAfterSeconds: 30
multiStageKargoAppSetHelmRepo: "https://github.com/kubriX-demo/kubriX-demo-oss"

teams:

# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubriX-demo/kubrix-apps
      path: demo-apps
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubriX-demo
    alerting:
      contactPoints:
        receivers:
          - uid: kubrix-team
            type: teams
            settings:
              url: ${KUBRIX_KUBRIX_MSTEAMS_WEBHOOK}
              # url: https://prod-199.westeurope.logic.azure.com:443/workflows/d18d802d1ef645b4a3ebde782d3f0257/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=k9XJNVAwQb3D-oJd1YHHihRftVcgJdfu2wU1Pj-kqqg
            disableResolveMessage: false