apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_alert: "1"
  name: kubernetes-alerts
data:
  notification-policy.yaml: |-
    apiVersion: 1
    policies:
        - orgId: 1
          receiver: grafana-default-email
          group_by:
            - grafana_folder
            - alertname
          routes:
{{- range .Values.teams }}
{{- if .alerting }}
            - receiver: {{ .name }}
              object_matchers:
                - - namespace
                  - =~
                  - {{ .name }}-.*
{{ end -}}
{{ end -}}