{{- range .Values.teams }}
{{- if .alerting }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_alert: "1"
  name: alerting-contact-point-{{ .name }}
data:
  contact-point-{{ .name }}.yaml: |-
    apiVersion: 1
    contactPoints:
        - orgId: 1
          name: {{ .name }}
{{ toYaml .alerting | indent 10 }}
---
{{ end -}}
{{ end -}}