apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_alert: "1"
  name: alerting-contact-points
data:
  contact-points.yaml: |-
    apiVersion: 1
    contactPoints:
        - orgId: 1
{{- range .Values.teams }}
{{- if .alerting }}
          name: {{ .name }}
{{ toYaml .alerting | indent 10 }}
{{ end -}}
{{ end -}}