
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-onboarding-alerting-secret
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: team-onboarding-alerting-secret
{{- range $team := .Values.teams }}
{{- if $team.alerting }}
{{- range $secret := $team.alerting.secrets }}
  data:
  - secretKey: {{ $secret }}
    remoteRef:
      key: kubrix-kv/data/{{ $team.name }}/observability
      property: {{ $secret }}
{{- end }}
{{- end }}
{{- end }}

