
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-onboarding-alerting-secret
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: team-onboarding-alerting-secret
  dataFrom:
  - find:
      name:
        regexp: "kubrix-kv/data/.*/observability/KUBRIX_ALERTING_.*"
