name: sync upstream with PR

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
         
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: fetch upstream commits and create PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add upstream https://github.com/suxess-it/kubriX.git
          git fetch upstream
          git switch -c from-upstream upstream/main
          git push --set-upstream origin from-upstream
          # create a PR unless there is already an existing PR from branch 'from-upstream'
          gh pr view from-upstream --repo ${GITHUB_REPOSITORY} --json state --jq '.state' | grep OPEN || gh pr create --base main --head from-upstream --repo ${GITHUB_REPOSITORY} --title "Updates from upstream" --body ""
